import type { Metadata } from 'next';
import { PlayfairDisplay } from './fonts';
import './globals.scss'
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />
      </head>
      <body
        className={`${PlayfairDisplay.className} h-screen`}
      >
        <div className='wraper min-h-full flex flex-col '>
          <Header></Header>
          <main className='flex-auto'>
            {children}
          </main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
